spring.application.name=gestionincidencias

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_incidencias
spring.datasource.username=postgres
spring.datasource.password=admin1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# Correo emisor para notificaciones.
# Para Gmail debes usar una contrasena de aplicacion, no tu contrasena normal.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=janeth.ramos0211@gmail.com
spring.mail.password=orjuiyhxaumnfwvi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.mail.soporte=janeth.ramos0211@gmail.com
app.mail.enviar-copia-soporte=true
