import { test, expect, type Page } from '@playwright/test';
const login = async (page: Page, role = 'ADMIN') => { await page.goto('/login'); await page.getByLabel('Correo electrónico').fill(`${role.toLowerCase()}@fixture.invalid`); await page.getByLabel('Contraseña', { exact: true }).fill('fixture-password'); await page.getByRole('button', { name: 'Entrar al sistema' }).click(); await expect(page).toHaveURL(/\/dashboard/); await expect(page.locator('#protected-app')).toBeVisible(); await expect(page.locator('#dashboard-status')).not.toHaveText('Cargando datos…'); await expect(page.locator('#refresh')).toBeEnabled(); };
test('raíz sin sesión y dashboard protegido redirigen a login', async ({ page }) => { await page.goto('/'); await expect(page).toHaveURL(/\/login/); await page.goto('/dashboard'); await expect(page).toHaveURL(/\/login/); });
for (const role of ['ADMIN', 'SUPERVISOR', 'AGENTE', 'CLIENTE']) {
    test(`login real Nest/BCrypt, métricas y navegación ${role}`, async ({ page }) => {
        await login(page, role); await expect(page.locator('#rolUsuario')).toHaveText(role); await expect(page.locator('#rolUsuario')).toBeVisible(); await expect(page.locator('#nombreUsuario')).toBeVisible(); await expect(page.locator('#totalOperativos')).toHaveText('1'); await expect(page.locator('#ticketsNuevos')).toHaveText('1');
        if (['ADMIN', 'SUPERVISOR'].includes(role)) { await expect(page.locator('[data-menu="usuarios"]')).toBeVisible(); await expect(page.locator('#totalUsuarios')).toHaveText('4'); }
        else { await expect(page.locator('[data-menu="usuarios"]')).toBeHidden(); await expect(page.locator('#totalUsuarios')).toHaveText('—'); }
        if (role === 'AGENTE') await expect(page.locator('[data-menu="crear-ticket"]')).toBeVisible();
        const stored = await page.evaluate(() => JSON.parse(sessionStorage.getItem('usuarioSistema')!)); expect(Object.keys(stored).sort()).toEqual(['id', 'nombre', 'rol', 'token']); expect(await page.locator('body').textContent()).not.toContain(stored.token);
    });
}
test('login incorrecto muestra error y no guarda sesión', async ({ page }) => { await page.goto('/login'); await page.getByLabel('Correo electrónico').fill('admin@fixture.invalid'); await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta'); await page.getByRole('button', { name: 'Entrar al sistema' }).click(); await expect(page.locator('#login-error')).toContainText('incorrecta'); expect(await page.evaluate(() => sessionStorage.getItem('usuarioSistema'))).toBeNull(); });
test('recargar restaura sesión y login existente redirige', async ({ page }) => { await login(page); await page.reload(); await expect(page.locator('#nombreUsuario')).toHaveText('Usuario ADMIN'); await page.goto('/login'); await expect(page).toHaveURL(/\/dashboard/); await page.goto('/'); await expect(page).toHaveURL(/\/dashboard/); });
test('logout elimina sesión', async ({ page }) => { await login(page); await page.getByRole('button', { name: 'Cerrar sesión' }).click(); await expect(page).toHaveURL(/\/login/); expect(await page.evaluate(() => sessionStorage.getItem('usuarioSistema'))).toBeNull(); });
test('sesión expirada o dañada no permite acceso', async ({ page }) => { await page.goto('/login'); await page.evaluate(() => sessionStorage.setItem('usuarioSistema', '{dañado')); await page.goto('/dashboard'); await expect(page).toHaveURL(/\/login/); await page.evaluate(() => sessionStorage.setItem('usuarioSistema', JSON.stringify({ id: 1, nombre: 'Usuario', rol: 'ADMIN', token: 'a.' + btoa(JSON.stringify({ exp: 1 })) + '.b' }))); await page.goto('/dashboard'); await expect(page).toHaveURL(/\/login/); });
test('401 de API limpia sesión y explica expiración', async ({ page }) => { await login(page); await page.route('**/api/tickets', (r) => r.fulfill({ status: 401, json: { message: 'Token vencido.' } })); await page.getByRole('button', { name: 'Actualizar', exact: true }).click(); await expect(page).toHaveURL(/\/login\?sesion=expirada/); await expect(page.locator('#login-error')).toContainText('expirado'); });
test('403 conserva sesión y muestra error', async ({ page }) => { await login(page); await page.route('**/api/tickets', (r) => r.fulfill({ status: 403, json: { message: 'Acceso denegado.' } })); await page.getByRole('button', { name: 'Actualizar', exact: true }).click(); await expect(page.locator('#dashboard-status')).toHaveText('Acceso denegado.'); await expect(page).toHaveURL(/\/dashboard/); });
test('payload login y Authorization centralizados', async ({ page }) => { let body: unknown; let jwt = ''; await page.route('**/api/auth/login', async (r) => { body = r.request().postDataJSON(); await r.continue(); }); await page.route('**/api/tickets', async (r) => { jwt = r.request().headers().authorization!; await r.continue(); }); await login(page); await expect(page.locator('#totalOperativos')).toHaveText('1'); expect(body).toEqual({ correo: 'admin@fixture.invalid', password: 'fixture-password' }); expect(jwt).toMatch(/^Bearer /); });
test('vacío no rompe cards ni tabla', async ({ page }) => { await page.route('**/api/tickets', (r) => r.fulfill({ json: [] })); await page.route('**/api/reportes/operacion-resumen', (r) => r.fulfill({ json: { totalOperativos: 0 } })); await login(page); await expect(page.locator('#totalOperativos')).toHaveText('0'); await expect(page.locator('#recent-tickets')).toContainText('No hay tickets'); await expect(page.locator('#estadoReporte')).toContainText('Sin datos'); });
test('JSON inválido se muestra sin romper página', async ({ page }) => { await page.route('**/api/tickets', (r) => r.fulfill({ contentType: 'text/html', body: '<html>Error</html>' })); await login(page); await expect(page.locator('#dashboard-status')).toContainText('respuesta no válida'); });
test('error de red tiene recuperación', async ({ page }) => { await login(page); await page.route('**/api/tickets', (r) => r.abort()); await page.getByRole('button', { name: 'Actualizar', exact: true }).click(); await expect(page.locator('#dashboard-status')).toContainText('No se pudo conectar'); await page.unroute('**/api/tickets'); await page.getByRole('button', { name: 'Actualizar', exact: true }).click(); await expect(page.locator('#dashboard-status')).toHaveText('Datos actualizados.'); });
test('flags ocultan recursos y navegación correspondientes', async ({ page }) => { await page.route('**/api/configuracion-sistema', (r) => r.fulfill({ json: { solicitudesRecursosActivo: false, reportesCliente: false } })); await login(page, 'CLIENTE'); await expect(page.locator('#resources')).toBeHidden(); await expect(page.locator('[data-menu="solicitudes-recursos"]')).toBeHidden(); await expect(page.locator('[data-menu="reportes"]')).toBeHidden(); });
test('reportes desactivados no bloquean dashboard ni estados históricos', async ({ page }) => { await page.route('**/api/reportes/operacion-resumen', (r) => r.fulfill({ status: 403, json: { message: 'Reportes desactivados.' } })); await page.route('**/api/tickets', (r) => r.fulfill({ json: [{ id: 1, titulo: 'Histórico', estado: 'RESUELTO', prioridad: 'P3_MEDIA', clienteId: 1 }] })); await login(page); await expect(page.locator('#ticketsEnProgreso')).toHaveText('1'); await expect(page.locator('#dashboard-status')).toHaveText('Datos actualizados.'); });
test('texto remoto se inserta sin ejecutar HTML', async ({ page }) => { await page.route('**/api/tickets', (r) => r.fulfill({ json: [{ id: 1, titulo: '<img src=x onerror=alert(1)>', estado: 'NUEVO', prioridad: 'P3_MEDIA', clienteId: 1 }] })); await login(page); await expect(page.locator('#recent-tickets')).toContainText('<img'); await expect(page.locator('#recent-tickets img')).toHaveCount(0); });
test('responsive móvil y sidebar colapsable', async ({ page }, testInfo) => { await page.goto('/login'); await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true }); await login(page); await expect(page.locator('#dashboard-status')).toHaveText('Datos actualizados.'); await page.screenshot({ path: testInfo.outputPath('dashboard.png'), fullPage: true }); await page.getByRole('button', { name: 'Ocultar barra lateral' }).click(); await expect(page.locator('#protected-app')).toHaveClass(/sidebar-colapsada/); await page.setViewportSize({ width: 390, height: 844 }); await expect(page.getByRole('button', { name: 'Cerrar sesión' })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: testInfo.outputPath('mobile.png'), fullPage: true }); });
test('recursos siguen disponibles si Reportes está desactivado', async ({ page }) => { await page.route('**/api/reportes/recursos-resumen', (r) => r.fulfill({ status: 403, json: { message: 'Reportes desactivados.' } })); await page.route('**/api/solicitudes-recursos', (r) => r.fulfill({ json: [{ estadoRecurso: 'ESPERANDO_PROVEEDOR', retrasada: true }] })); await login(page); await expect(page.locator('#esperandoProveedor')).toHaveText('1'); await expect(page.locator('#retrasadas')).toHaveText('1'); });
test('listado filtra tickets que el backend autoriza para cada rol', async ({ page }) => {
    const expected: Record<string, number> = { ADMIN: 3, SUPERVISOR: 2, AGENTE: 1, CLIENTE: 2 };
    for (const role of Object.keys(expected)) { await login(page, role); await page.goto('/tickets'); await expect(page.locator('#tickets-body tr')).toHaveCount(expected[role]!); await page.evaluate(() => sessionStorage.clear()); }
});
test('filtros legacy de búsqueda, compañía, proyecto, tipo, estado, prioridad y atención', async ({ page }) => {
    await login(page); await page.goto('/tickets'); await expect(page.locator('#tickets-body tr')).toHaveCount(3);
    await page.getByLabel('Compañía').selectOption('2'); await expect(page.locator('#tickets-body')).toContainText('Otro proyecto'); await expect(page.locator('#tickets-body tr')).toHaveCount(1);
    await page.getByLabel('Compañía').selectOption(''); await page.getByLabel('Proyecto').selectOption('1'); await page.getByLabel('Tipo de incidencia').selectOption('9'); await page.getByLabel('Tipo de atención').selectOption('RECURSO_EXTERNO'); await page.getByLabel('Estado').selectOption('EN_PROGRESO'); await page.getByLabel('Prioridad').selectOption('P3_MEDIA'); await page.getByLabel('Buscar ticket').fill('INC-2026-0101'); await expect(page.locator('#tickets-body tr')).toHaveCount(1); await expect(page.locator('#tickets-body')).toContainText('INC-2026-0101');
});
test('filtro de cliente y proyecto proveniente de la URL', async ({ page }) => { await login(page); await page.goto('/tickets?proyectoId=1'); await expect(page.locator('#filter-project')).toHaveValue('1'); await page.getByLabel('Cliente').selectOption('4'); await expect(page.locator('#tickets-body tr')).toHaveCount(2); });
test('listado vacío, estado loading y error de API', async ({ page }) => {
    await page.route('**/api/tickets', async (r) => { await new Promise((resolve) => setTimeout(resolve, 400)); await r.fulfill({ json: [] }); }); await login(page); await page.goto('/tickets'); await expect(page.locator('#list-status')).toContainText('Cargando'); await expect(page.locator('#tickets-body')).toContainText('No hay tickets');
    await page.route('**/api/tickets', (r) => r.fulfill({ status: 500, json: { message: 'Error de prueba.' } })); await page.reload(); await expect(page.locator('#list-status')).toContainText('Error de prueba.'); await page.getByRole('button', { name: 'Reintentar' }).click(); await expect(page.locator('#list-status')).toContainText('Error de prueba.');
});
test('401 en el listado limpia sesión y redirige', async ({ page }) => { await login(page); await page.route('**/api/tickets', (r) => r.fulfill({ status: 401, json: { message: 'Expirado.' } })); await page.goto('/tickets'); await expect(page).toHaveURL(/\/login\?sesion=expirada/); });
test('detalle muestra datos, fechas SLA, recurso externo, comentarios, historial y adjuntos', async ({ page }) => {
    await login(page); await page.goto('/tickets/101'); await expect(page.locator('#ticket-content')).toBeVisible(); await expect(page.locator('#ticket-number')).toHaveText('INC-2026-0101'); await expect(page.locator('#ticket-title')).toHaveText('Acceso externo'); await expect(page.locator('#ticket-resolution-sla')).toContainText('No aplica'); await expect(page.locator('#resource-section')).toBeVisible(); await expect(page.locator('#resource-provider')).toHaveText('Proveedor de prueba'); await expect(page.locator('#history-list')).toContainText('No hay historial registrado'); await expect(page.locator('#attachments-list tr')).toContainText('Este ticket no tiene archivos'); await expect(page.locator('body')).not.toContainText('rutaArchivo');
});
test('detalle permitido por alcance CLIENTE y AGENTE', async ({ page }) => { await login(page, 'CLIENTE'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await expect(page.locator('#comment-visibility option')).toHaveCount(1); await page.evaluate(() => sessionStorage.clear()); await login(page, 'AGENTE'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); });
test('detalle ajeno 403, ticket inexistente y ruta inválida', async ({ page }) => { await login(page, 'CLIENTE'); await page.goto('/tickets/200'); await expect(page.locator('#detail-status')).toHaveText('No tienes acceso a este ticket.'); await page.goto('/tickets/999'); await expect(page.locator('#detail-status')).toContainText('Ticket no encontrado'); await page.goto('/tickets/abc'); await expect(page.locator('#detail-status')).toContainText('no es válido'); });
test('401 en detalle redirige a login', async ({ page }) => { await login(page); await page.route('**/api/tickets/100', (r) => r.fulfill({ status: 401, json: { message: 'Token expirado.' } })); await page.goto('/tickets/100'); await expect(page).toHaveURL(/\/login\?sesion=expirada/); });
test('comentario público permitido y se recarga con feedback', async ({ page }) => { await login(page, 'CLIENTE'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await page.getByLabel('Comentario').fill('La conexión ya funciona.'); await page.getByRole('button', { name: 'Agregar comentario' }).click(); await expect(page.locator('#comment-status')).toHaveText('Comentario guardado.'); await expect(page.locator('#comments-list')).toContainText('La conexión ya funciona.'); });
test('comentario INTERNO denegado a CLIENTE sin perder la página', async ({ page }) => { await login(page, 'CLIENTE'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await page.evaluate(() => { const s = document.querySelector<HTMLSelectElement>('#comment-visibility')!; s.disabled = false; s.add(new Option('Interno', 'INTERNO')); s.value = 'INTERNO'; }); await page.getByLabel('Comentario').fill('No permitido'); await page.getByRole('button', { name: 'Agregar comentario' }).click(); await expect(page.locator('#comment-status')).toContainText('No puedes crear'); await expect(page).toHaveURL(/\/tickets\/100/); });
test('rol interno agrega comentario visible y texto se inserta como texto', async ({ page }) => { await login(page, 'AGENTE'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await page.getByLabel('Visibilidad').selectOption('INTERNO'); await page.getByLabel('Comentario').fill('<img src=x onerror=alert(1)>'); await page.getByRole('button', { name: 'Agregar comentario' }).click(); await expect(page.locator('#comments-list')).toContainText('<img'); await expect(page.locator('#comments-list img')).toHaveCount(0); await expect(page.locator('#comment-status')).toHaveText('Comentario guardado.'); });
test('comentario de cliente no muestra entradas internas del backend', async ({ page }) => { await login(page, 'CLIENTE'); await page.goto('/tickets/100'); await expect(page.locator('#comments-list')).toContainText('Comentario público'); await expect(page.locator('#comments-list')).not.toContainText('Nota interna'); });
test('historial conserva orden descendente y cliente solo ve su historial', async ({ page }) => { await login(page, 'ADMIN'); await page.goto('/tickets/100'); await expect(page.locator('#history-list .ticket-history-item')).toHaveCount(2); await expect(page.locator('#history-list .ticket-history-item').first()).toContainText('CAMBIO_PRIORIDAD'); await page.evaluate(() => sessionStorage.clear()); await login(page, 'CLIENTE'); await page.goto('/tickets/100'); await expect(page.locator('#history-list .ticket-history-item')).toHaveCount(1); });
test('subida válida adjunta nombre/tamaño y descarga el archivo', async ({ page }) => { await login(page, 'ADMIN'); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await page.locator('#attachment').setInputFiles({ name: 'notas.txt', mimeType: 'text/plain', buffer: Buffer.from('nota') }); await page.getByRole('button', { name: 'Subir archivo' }).click(); await expect(page.locator('#attachment-status')).toHaveText('Archivo subido correctamente.'); await expect(page.locator('#attachments-list')).toContainText('notas.txt'); const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Descargar' }).last().click(); expect((await download).suggestedFilename()).toBe('notas.txt'); });
test('subida inválida de tipo y exceso de tamaño se bloquea', async ({ page }) => { await login(page); await page.goto('/tickets/100'); await expect(page.locator('#ticket-content')).toBeVisible(); await page.locator('#attachment').setInputFiles({ name: 'payload.exe', mimeType: 'application/octet-stream', buffer: Buffer.from('x') }); await page.getByRole('button', { name: 'Subir archivo' }).click(); await expect(page.locator('#attachment-status')).toContainText('Tipo de archivo no permitido'); await page.locator('#attachment').setInputFiles({ name: 'large.pdf', mimeType: 'application/pdf', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) }); await page.getByRole('button', { name: 'Subir archivo' }).click(); await expect(page.locator('#attachment-status')).toContainText('10 MB'); await expect(page.locator('#attachments-list')).not.toContainText('payload.exe'); });
