spring.application.name=gestionincidencias

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_incidencias
spring.datasource.username=postgres
spring.datasource.password=admin1

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

# =========================================
# CONFIGURACIÓN DE CORREO
# =========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO_EMISOR@gmail.com
spring.mail.password=TU_PASSWORD_DE_APLICACION
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8