--
-- PostgreSQL database dump
--

\restrict FxUaoVg1UNryePJkaF31RShTii6G4Miu2qNkEQHI6c9lhinZKmNTuio10kzKOve

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: adjuntos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.adjuntos (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    nombre_archivo character varying(255) NOT NULL,
    ruta_archivo character varying(500) NOT NULL,
    tipo_archivo character varying(100),
    tamanio bigint,
    fecha_subida timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: adjuntos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.adjuntos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: adjuntos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.adjuntos_id_seq OWNED BY public.adjuntos.id;


--
-- Name: auditoria_configuracion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_configuracion (
    id integer NOT NULL,
    crear_ticket_anterior boolean NOT NULL,
    crear_ticket_nuevo boolean NOT NULL,
    fecha_cambio timestamp(6) without time zone NOT NULL,
    historial_anterior boolean NOT NULL,
    historial_nuevo boolean NOT NULL,
    reportes_anterior boolean NOT NULL,
    reportes_nuevo boolean NOT NULL,
    usuario_correo character varying(150) NOT NULL,
    usuario_id integer,
    usuario_nombre character varying(200) NOT NULL,
    variante_anterior character varying(1) NOT NULL,
    variante_nueva character varying(1) NOT NULL,
    modulo character varying(100),
    rol character varying(50),
    valor_anterior character varying(100),
    valor_nuevo character varying(100)
);


--
-- Name: auditoria_configuracion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_configuracion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_configuracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: codigos_recuperacion_password; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.codigos_recuperacion_password (
    id integer NOT NULL,
    codigo character varying(100) NOT NULL,
    correo character varying(150) NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    fecha_expiracion timestamp(6) without time zone NOT NULL,
    usado boolean NOT NULL,
    intentos_fallidos integer DEFAULT 0 NOT NULL
);


--
-- Name: codigos_recuperacion_password_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.codigos_recuperacion_password ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.codigos_recuperacion_password_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comentarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comentarios (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    usuario_id integer NOT NULL,
    contenido text NOT NULL,
    tipo_comentario character varying(20) NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: comentarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.comentarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: comentarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.comentarios_id_seq OWNED BY public.comentarios.id;


--
-- Name: companias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companias (
    id integer NOT NULL,
    descripcion text,
    estado boolean NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(150) NOT NULL
);


--
-- Name: companias_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion_sistema; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.configuracion_sistema (
    id integer NOT NULL,
    crear_ticket_activo boolean NOT NULL,
    historial_activo boolean NOT NULL,
    reportes_activos boolean NOT NULL,
    variante_visual character varying(1) NOT NULL,
    crear_ticket_cliente boolean DEFAULT true NOT NULL,
    crear_ticket_agente boolean DEFAULT true NOT NULL,
    crear_ticket_supervisor boolean DEFAULT true NOT NULL,
    crear_ticket_admin boolean DEFAULT true NOT NULL,
    reportes_cliente boolean DEFAULT true NOT NULL,
    reportes_agente boolean DEFAULT true NOT NULL,
    reportes_supervisor boolean DEFAULT true NOT NULL,
    reportes_admin boolean DEFAULT true NOT NULL,
    historial_cliente boolean DEFAULT true NOT NULL,
    historial_agente boolean DEFAULT true NOT NULL,
    historial_supervisor boolean DEFAULT true NOT NULL,
    historial_admin boolean DEFAULT true NOT NULL,
    solicitudes_recursos_activo boolean DEFAULT true NOT NULL,
    solicitudes_recursos_cliente boolean DEFAULT true NOT NULL,
    solicitudes_recursos_agente boolean DEFAULT true NOT NULL,
    solicitudes_recursos_supervisor boolean DEFAULT true NOT NULL,
    solicitudes_recursos_admin boolean DEFAULT true NOT NULL
);


--
-- Name: configuracion_sistema_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.configuracion_sistema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_sistema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enlaces_compartidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enlaces_compartidos (
    id bigint NOT NULL,
    ticket_id integer NOT NULL,
    creado_por integer NOT NULL,
    correo_destinatario character varying(150) NOT NULL,
    token character varying(150) NOT NULL,
    puede_ver boolean DEFAULT true NOT NULL,
    puede_comentar boolean DEFAULT false NOT NULL,
    puede_ver_adjuntos boolean DEFAULT false NOT NULL,
    puede_subir_adjuntos boolean DEFAULT false NOT NULL,
    puede_cambiar_estado boolean DEFAULT false NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_expiracion timestamp without time zone,
    activo boolean DEFAULT true NOT NULL
);


--
-- Name: enlaces_compartidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.enlaces_compartidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: enlaces_compartidos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.enlaces_compartidos_id_seq OWNED BY public.enlaces_compartidos.id;


--
-- Name: historial_tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_tickets (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    usuario_id integer,
    accion character varying(50) NOT NULL,
    valor_anterior text,
    valor_nuevo text,
    descripcion text,
    fecha_creacion timestamp without time zone
);


--
-- Name: historial_tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.historial_tickets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: historial_tickets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.historial_tickets_id_seq OWNED BY public.historial_tickets.id;


--
-- Name: proyectos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.proyectos (
    id integer NOT NULL,
    descripcion text,
    estado boolean NOT NULL,
    fecha_actualizacion timestamp(6) without time zone NOT NULL,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(150) NOT NULL,
    compania_id integer NOT NULL
);


--
-- Name: proyectos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.proyectos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyectos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.roles_id_seq OWNED BY public.roles.id;


--
-- Name: solicitudes_recurso; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitudes_recurso (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    categoria character varying(80) NOT NULL,
    recurso character varying(150) NOT NULL,
    cantidad integer DEFAULT 1 NOT NULL,
    proveedor character varying(150),
    estado_recurso character varying(40) DEFAULT 'NUEVO'::character varying NOT NULL,
    fecha_solicitud_proveedor timestamp without time zone,
    fecha_estimada_entrega timestamp without time zone,
    fecha_recepcion timestamp without time zone,
    fecha_entrega_cliente timestamp without time zone,
    observaciones text,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_actualizacion timestamp without time zone,
    fecha_notificacion_retraso timestamp(6) without time zone,
    detalle_retraso text,
    fecha_estimada_entrega_original timestamp(6) without time zone,
    motivo_retraso character varying(100),
    CONSTRAINT chk_solicitud_recurso_cantidad CHECK ((cantidad > 0)),
    CONSTRAINT chk_solicitud_recurso_estado CHECK (((estado_recurso)::text = ANY (ARRAY[('NUEVO'::character varying)::text, ('EN_VALIDACION'::character varying)::text, ('SOLICITADO_PROVEEDOR'::character varying)::text, ('ESPERANDO_PROVEEDOR'::character varying)::text, ('RECIBIDO'::character varying)::text, ('ENTREGADO'::character varying)::text, ('CERRADO'::character varying)::text, ('CANCELADO'::character varying)::text])))
);


--
-- Name: solicitudes_recurso_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.solicitudes_recurso_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: solicitudes_recurso_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.solicitudes_recurso_id_seq OWNED BY public.solicitudes_recurso.id;


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id integer NOT NULL,
    numero_ticket character varying(30) NOT NULL,
    titulo character varying(150) NOT NULL,
    descripcion text NOT NULL,
    tipo_incidencia_id integer NOT NULL,
    cliente_id integer NOT NULL,
    agente_asignado_id integer,
    estado character varying(30) DEFAULT 'NUEVO'::character varying NOT NULL,
    prioridad character varying(30) DEFAULT 'P4_BAJA'::character varying NOT NULL,
    severidad character varying(30),
    criticidad character varying(30),
    impacto character varying(30),
    urgencia character varying(30),
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_resolucion timestamp without time zone,
    fecha_limite_resolucion timestamp(6) without time zone,
    fecha_limite_respuesta timestamp(6) without time zone,
    fecha_primera_respuesta timestamp(6) without time zone,
    sla_resolucion_cumplido boolean,
    sla_respuesta_cumplido boolean,
    proyecto_id integer NOT NULL,
    tipo_atencion character varying(30) DEFAULT 'OPERATIVO'::character varying NOT NULL,
    fecha_cierre timestamp(6) without time zone,
    CONSTRAINT chk_ticket_tipo_atencion CHECK (((tipo_atencion)::text = ANY (ARRAY[('OPERATIVO'::character varying)::text, ('RECURSO_EXTERNO'::character varying)::text])))
);


--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tickets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tickets_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tickets_id_seq OWNED BY public.tickets.id;


--
-- Name: tipos_incidencia; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tipos_incidencia (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    estado boolean DEFAULT true
);


--
-- Name: tipos_incidencia_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tipos_incidencia_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tipos_incidencia_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tipos_incidencia_id_seq OWNED BY public.tipos_incidencia.id;


--
-- Name: usuario_proyectos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_proyectos (
    id integer NOT NULL,
    estado boolean NOT NULL,
    fecha_asignacion timestamp(6) without time zone NOT NULL,
    proyecto_id integer NOT NULL,
    usuario_id integer NOT NULL
);


--
-- Name: usuario_proyectos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario_proyectos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_proyectos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario_roles (
    id integer NOT NULL,
    usuario_id integer NOT NULL,
    rol_id integer NOT NULL
);


--
-- Name: usuario_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuario_roles_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuario_roles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuario_roles_id_seq OWNED BY public.usuario_roles.id;


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id integer NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    correo character varying(150) NOT NULL,
    password character varying(100) NOT NULL,
    telefono character varying(20),
    estado boolean DEFAULT true,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usuarios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: adjuntos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos ALTER COLUMN id SET DEFAULT nextval('public.adjuntos_id_seq'::regclass);


--
-- Name: comentarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios ALTER COLUMN id SET DEFAULT nextval('public.comentarios_id_seq'::regclass);


--
-- Name: enlaces_compartidos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enlaces_compartidos ALTER COLUMN id SET DEFAULT nextval('public.enlaces_compartidos_id_seq'::regclass);


--
-- Name: historial_tickets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_tickets ALTER COLUMN id SET DEFAULT nextval('public.historial_tickets_id_seq'::regclass);


--
-- Name: roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles ALTER COLUMN id SET DEFAULT nextval('public.roles_id_seq'::regclass);


--
-- Name: solicitudes_recurso id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes_recurso ALTER COLUMN id SET DEFAULT nextval('public.solicitudes_recurso_id_seq'::regclass);


--
-- Name: tickets id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets ALTER COLUMN id SET DEFAULT nextval('public.tickets_id_seq'::regclass);


--
-- Name: tipos_incidencia id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_incidencia ALTER COLUMN id SET DEFAULT nextval('public.tipos_incidencia_id_seq'::regclass);


--
-- Name: usuario_roles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles ALTER COLUMN id SET DEFAULT nextval('public.usuario_roles_id_seq'::regclass);


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Data for Name: adjuntos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.adjuntos (id, ticket_id, nombre_archivo, ruta_archivo, tipo_archivo, tamanio, fecha_subida) FROM stdin;
\.


--
-- Data for Name: auditoria_configuracion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auditoria_configuracion (id, crear_ticket_anterior, crear_ticket_nuevo, fecha_cambio, historial_anterior, historial_nuevo, reportes_anterior, reportes_nuevo, usuario_correo, usuario_id, usuario_nombre, variante_anterior, variante_nueva, modulo, rol, valor_anterior, valor_nuevo) FROM stdin;
18	t	t	2026-10-01 16:21:09.337118	f	t	f	t	admin.prueba@correo.com	12	Admin Prueba	A	A	REPORTES	GLOBAL	false	true
19	t	t	2026-10-01 16:21:09.527885	f	t	f	t	admin.prueba@correo.com	12	Admin Prueba	A	A	HISTORIAL	GLOBAL	false	true
\.


--
-- Data for Name: codigos_recuperacion_password; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.codigos_recuperacion_password (id, codigo, correo, fecha_creacion, fecha_expiracion, usado, intentos_fallidos) FROM stdin;
\.


--
-- Data for Name: comentarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.comentarios (id, ticket_id, usuario_id, contenido, tipo_comentario, fecha_creacion) FROM stdin;
\.


--
-- Data for Name: companias; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.companias (id, descripcion, estado, fecha_actualizacion, fecha_creacion, nombre) FROM stdin;
4	Empresa tecnológica dedicada a servicios corporativos e infraestructura.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	NovaTech Solutions
5	Empresa dedicada a logística, transporte y operaciones de distribución.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	BlueWave Logistics
6	Empresa de servicios administrativos y soluciones corporativas.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Grupo Horizonte
\.


--
-- Data for Name: configuracion_sistema; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.configuracion_sistema (id, crear_ticket_activo, historial_activo, reportes_activos, variante_visual, crear_ticket_cliente, crear_ticket_agente, crear_ticket_supervisor, crear_ticket_admin, reportes_cliente, reportes_agente, reportes_supervisor, reportes_admin, historial_cliente, historial_agente, historial_supervisor, historial_admin, solicitudes_recursos_activo, solicitudes_recursos_cliente, solicitudes_recursos_agente, solicitudes_recursos_supervisor, solicitudes_recursos_admin) FROM stdin;
1	t	t	t	A	t	t	t	t	t	t	t	t	t	t	t	t	t	t	t	t	t
\.


--
-- Data for Name: enlaces_compartidos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.enlaces_compartidos (id, ticket_id, creado_por, correo_destinatario, token, puede_ver, puede_comentar, puede_ver_adjuntos, puede_subir_adjuntos, puede_cambiar_estado, fecha_creacion, fecha_expiracion, activo) FROM stdin;
\.


--
-- Data for Name: historial_tickets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.historial_tickets (id, ticket_id, usuario_id, accion, valor_anterior, valor_nuevo, descripcion, fecha_creacion) FROM stdin;
65	24	15	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0001.	2026-10-01 13:23:39.418201
66	25	16	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0002.	2026-10-01 09:23:39.418201
67	26	17	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0003.	2026-09-30 15:23:39.418201
68	27	18	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0004.	2026-09-29 15:23:39.418201
69	28	15	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0005.	2026-09-27 15:23:39.418201
70	29	17	CREACION_TICKET	\N	NUEVO	Se creó el ticket INC-2026-0006.	2026-09-30 15:23:39.418201
71	25	13	ASIGNACION_AGENTE	SIN_ASIGNAR	Agente Demo	Se asignó el ticket al agente Agente Demo.	2026-10-01 10:23:39.418201
72	26	13	ASIGNACION_AGENTE	SIN_ASIGNAR	Agente Demo	Se asignó el ticket al agente Agente Demo.	2026-09-30 16:23:39.418201
73	27	13	ASIGNACION_AGENTE	SIN_ASIGNAR	Agente Demo	Se asignó el ticket al agente Agente Demo.	2026-09-29 16:23:39.418201
74	28	13	ASIGNACION_AGENTE	SIN_ASIGNAR	Agente Demo	Se asignó el ticket al agente Agente Demo.	2026-09-27 16:23:39.418201
75	29	13	ASIGNACION_AGENTE	SIN_ASIGNAR	Agente Demo	Se asignó el ticket al agente Agente Demo.	2026-09-30 16:23:39.418201
76	25	13	CAMBIO_ESTADO	NUEVO	EN_PROGRESO	Se cambió el estado automáticamente por la asignación del agente.	2026-10-01 10:23:39.418201
77	26	13	CAMBIO_ESTADO	NUEVO	EN_PROGRESO	Se cambió el estado automáticamente por la asignación del agente.	2026-09-30 16:23:39.418201
78	27	13	CAMBIO_ESTADO	NUEVO	EN_PROGRESO	Se cambió el estado automáticamente por la asignación del agente.	2026-09-29 16:23:39.418201
79	28	13	CAMBIO_ESTADO	NUEVO	EN_PROGRESO	Se cambió el estado automáticamente por la asignación del agente.	2026-09-27 16:23:39.418201
80	29	13	CAMBIO_ESTADO	NUEVO	EN_PROGRESO	Se cambió el estado automáticamente por la asignación del agente.	2026-09-30 16:23:39.418201
81	27	14	CAMBIO_ESTADO	EN_PROGRESO	CERRADO	Se cambió el estado del ticket de EN_PROGRESO a CERRADO. Nota de cierre: Se reinstaló el controlador de impresión y se realizaron pruebas correctamente.	2026-09-30 15:23:39.418201
82	28	14	CAMBIO_ESTADO	EN_PROGRESO	CERRADO	Se cambió el estado del ticket de EN_PROGRESO a CERRADO. Nota de cierre: Se corrigió la configuración del módulo y se validó el acceso a reportes.	2026-09-28 15:23:39.418201
83	29	17	RECURSO_CREADO	\N	NUEVO	Se creó la solicitud de recurso. Categoría: Hardware. Recurso: Memoria RAM DDR4 16 GB. Cantidad: 2.	2026-09-30 15:23:39.418201
\.


--
-- Data for Name: proyectos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.proyectos (id, descripcion, estado, fecha_actualizacion, fecha_creacion, nombre, compania_id) FROM stdin;
3	Atención de incidencias generales de usuarios corporativos.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Soporte Corporativo	4
4	Gestión de servidores, redes y componentes de infraestructura.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Infraestructura TI	4
5	Gestión de accesos, credenciales y seguridad de usuarios.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Seguridad y Accesos	4
6	Seguimiento de reemplazos y actualización de equipos tecnológicos.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Renovación de Equipos	4
7	Atención general de solicitudes e incidencias de usuarios.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Mesa de Ayuda	5
8	Soporte a equipos y sistemas utilizados en bodegas.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Operaciones de Bodega	5
9	Soporte a la plataforma utilizada para operaciones de transporte.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Plataforma de Transporte	5
10	Administración y soporte de dispositivos utilizados por el personal.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Gestión de Dispositivos	5
11	Atención tecnológica para áreas administrativas.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Soporte Administrativo	6
12	Soporte de aplicaciones y accesos utilizados por el área financiera.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Sistemas Financieros	6
13	Soporte y mantenimiento funcional del portal interno corporativo.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Portal Interno	6
14	Gestión de incidencias relacionadas con computadoras y periféricos.	t	2026-10-01 15:16:09.761329	2026-10-01 15:16:09.761329	Equipos y Periféricos	6
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (id, nombre, descripcion) FROM stdin;
1	CLIENTE	Usuario que reporta incidencias
2	AGENTE	Usuario que atiende tickets
3	SUPERVISOR	Usuario que supervisa tickets y métricas
4	ADMIN	Usuario administrador del sistema
\.


--
-- Data for Name: solicitudes_recurso; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.solicitudes_recurso (id, ticket_id, categoria, recurso, cantidad, proveedor, estado_recurso, fecha_solicitud_proveedor, fecha_estimada_entrega, fecha_recepcion, fecha_entrega_cliente, observaciones, fecha_creacion, fecha_actualizacion, fecha_notificacion_retraso, detalle_retraso, fecha_estimada_entrega_original, motivo_retraso) FROM stdin;
3	29	Hardware	Memoria RAM DDR4 16 GB	2	Proveedor Demo	ESPERANDO_PROVEEDOR	2026-09-30 21:23:39.418201	2026-10-04 15:23:39.418201	\N	\N	Solicitud creada como dato de demostración para seguimiento de recurso externo.	2026-09-30 15:23:39.418201	2026-10-01 12:23:39.418201	\N	\N	2026-10-04 15:23:39.418201	\N
\.


--
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tickets (id, numero_ticket, titulo, descripcion, tipo_incidencia_id, cliente_id, agente_asignado_id, estado, prioridad, severidad, criticidad, impacto, urgencia, fecha_creacion, fecha_actualizacion, fecha_resolucion, fecha_limite_resolucion, fecha_limite_respuesta, fecha_primera_respuesta, sla_resolucion_cumplido, sla_respuesta_cumplido, proyecto_id, tipo_atencion, fecha_cierre) FROM stdin;
24	INC-2026-0001	No puedo iniciar sesión en el portal corporativo	El usuario indica que recibe un mensaje de credenciales inválidas al intentar acceder al portal.	1	15	\N	NUEVO	P2_ALTA	MEDIA	MEDIA	ALTO	MEDIA	2026-10-01 13:23:39.418201	2026-10-01 13:23:39.418201	\N	2026-10-01 21:23:39.418201	2026-10-01 14:23:39.418201	\N	\N	\N	3	OPERATIVO	\N
25	INC-2026-0002	Cuenta bloqueada después de cambio de contraseña	La cuenta quedó bloqueada luego de varios intentos de acceso posteriores al cambio de contraseña.	1	16	14	EN_PROGRESO	P2_ALTA	MEDIA	ALTA	ALTO	MEDIA	2026-10-01 09:23:39.418201	2026-10-01 11:23:39.418201	\N	2026-10-01 17:23:39.418201	2026-10-01 10:23:39.418201	2026-10-01 10:23:39.418201	\N	t	5	OPERATIVO	\N
26	INC-2026-0003	Lector de código de barras no responde	El lector utilizado en bodega dejó de reconocer códigos y requiere revisión técnica.	4	17	14	EN_PROGRESO	P3_MEDIA	MEDIA	MEDIA	MEDIO	MEDIA	2026-09-30 15:23:39.418201	2026-10-01 10:23:39.418201	\N	2026-10-01 15:23:39.418201	2026-09-30 19:23:39.418201	2026-09-30 19:23:39.418201	\N	t	8	OPERATIVO	\N
27	INC-2026-0004	Impresora de recepción no imprime	La impresora aparece conectada pero no procesa los documentos enviados desde el equipo de recepción.	4	18	14	CERRADO	P3_MEDIA	MEDIA	MEDIA	MEDIO	MEDIA	2026-09-29 15:23:39.418201	2026-09-30 15:23:39.418201	2026-09-30 15:23:39.418201	2026-09-30 15:23:39.418201	2026-09-29 19:23:39.418201	2026-09-29 16:23:39.418201	t	t	14	OPERATIVO	2026-09-30 15:23:39.418201
28	INC-2026-0005	Portal interno muestra error al cargar reportes	Al ingresar al módulo de reportes del portal interno se muestra un error y la información no carga.	2	15	14	CERRADO	P2_ALTA	ALTA	MEDIA	ALTO	MEDIA	2026-09-27 15:23:39.418201	2026-09-28 15:23:39.418201	2026-09-28 15:23:39.418201	2026-09-27 23:23:39.418201	2026-09-27 16:23:39.418201	2026-09-27 17:23:39.418201	f	f	13	OPERATIVO	2026-09-28 15:23:39.418201
29	INC-2026-0006	Solicitud de reemplazo de memoria RAM	El equipo presenta fallas de memoria y requiere reemplazo de dos módulos RAM para continuar su operación normal.	3	17	14	EN_PROGRESO	P3_MEDIA	MEDIA	MEDIA	MEDIO	MEDIA	2026-09-30 15:23:39.418201	2026-10-01 12:23:39.418201	\N	\N	2026-09-30 19:23:39.418201	2026-09-30 19:23:39.418201	\N	t	6	RECURSO_EXTERNO	\N
\.


--
-- Data for Name: tipos_incidencia; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tipos_incidencia (id, nombre, descripcion, estado) FROM stdin;
1	Acceso al sistema	Problemas relacionados con inicio de sesión o permisos	t
2	Error en plataforma	Errores funcionales o técnicos del sistema	t
3	Solicitud de soporte	Solicitudes generales de ayuda	t
4	Problema técnico	Incidencias técnicas reportadas por el cliente	t
5	Consulta general	Preguntas o consultas no críticas	t
\.


--
-- Data for Name: usuario_proyectos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuario_proyectos (id, estado, fecha_asignacion, proyecto_id, usuario_id) FROM stdin;
8	t	2026-10-01 15:23:39.418201	3	13
9	t	2026-10-01 15:23:39.418201	4	13
10	t	2026-10-01 15:23:39.418201	5	13
11	t	2026-10-01 15:23:39.418201	6	13
12	t	2026-10-01 15:23:39.418201	7	13
13	t	2026-10-01 15:23:39.418201	8	13
14	t	2026-10-01 15:23:39.418201	9	13
15	t	2026-10-01 15:23:39.418201	10	13
16	t	2026-10-01 15:23:39.418201	11	13
17	t	2026-10-01 15:23:39.418201	12	13
18	t	2026-10-01 15:23:39.418201	13	13
19	t	2026-10-01 15:23:39.418201	14	13
20	t	2026-10-01 15:23:39.418201	3	14
21	t	2026-10-01 15:23:39.418201	4	14
22	t	2026-10-01 15:23:39.418201	5	14
23	t	2026-10-01 15:23:39.418201	6	14
24	t	2026-10-01 15:23:39.418201	7	14
25	t	2026-10-01 15:23:39.418201	8	14
26	t	2026-10-01 15:23:39.418201	9	14
27	t	2026-10-01 15:23:39.418201	10	14
28	t	2026-10-01 15:23:39.418201	11	14
29	t	2026-10-01 15:23:39.418201	12	14
30	t	2026-10-01 15:23:39.418201	13	14
31	t	2026-10-01 15:23:39.418201	14	14
32	t	2026-10-01 15:23:39.418201	3	15
33	t	2026-10-01 15:23:39.418201	7	15
34	t	2026-10-01 15:23:39.418201	13	15
35	t	2026-10-01 15:23:39.418201	5	16
36	t	2026-10-01 15:23:39.418201	4	16
37	t	2026-10-01 15:23:39.418201	12	16
38	t	2026-10-01 15:23:39.418201	6	17
39	t	2026-10-01 15:23:39.418201	9	17
40	t	2026-10-01 15:23:39.418201	8	17
41	t	2026-10-01 15:23:39.418201	10	18
42	t	2026-10-01 15:23:39.418201	14	18
43	t	2026-10-01 15:23:39.418201	11	18
\.


--
-- Data for Name: usuario_roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuario_roles (id, usuario_id, rol_id) FROM stdin;
12	12	4
13	13	3
14	14	2
15	15	1
16	16	1
17	17	1
18	18	1
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios (id, nombre, apellido, correo, password, telefono, estado, fecha_creacion) FROM stdin;
13	Supervisor	Demo	supervisor.demo@correo.com	$2a$10$LKIQkIj3G0WiwlSPBwIMPes2PMeqMNfdKyOaph45otRBcLgnscu82	\N	t	2026-10-01 15:16:09.761329
14	Agente	Demo	agente.demo@correo.com	$2a$10$yJynCMEAKxhfCafnV3/ljuhh2SzvHwybndh6sQz22WqgJrAhBqWlG	\N	t	2026-10-01 15:16:09.761329
15	Cliente	Demo	cliente.demo@correo.com	$2a$10$Eg67HBSUczT8cECCua2bWOLbHbbDxyNhylIkmkqM9Lk4DwJJ7wM3G	\N	t	2026-10-01 15:16:09.761329
16	Ana	Torres	ana.torres@correo.com	$2a$10$sPJ4zCdufPkee2A1y1xereabridy.giE4UNs6.9Ylot0SMeccev/2	\N	t	2026-10-01 15:23:39.418201
17	Luis	Mendoza	luis.mendoza@correo.com	$2a$10$Bo1gXkqFl/W1IEQ8lowm0uV.CpCwyYn90NLF7JGSKXh64DZ.A/BGa	\N	t	2026-10-01 15:23:39.418201
18	Carla	Rivera	carla.rivera@correo.com	$2a$10$0QcciGz13MXA1NG1IyBC8e5iyRrDqnjObV/GJV40DcyTrZl7AE7ni	\N	t	2026-10-01 15:23:39.418201
12	Admin	Prueba	admin.prueba@correo.com	$2a$10$.kIhNE.J1tM2W7wn9HJow.CMs9KxrfM2riZ5ikbOHKHpPaIsIi7F2	\N	t	2026-10-01 14:18:03.486968
\.


--
-- Name: adjuntos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.adjuntos_id_seq', 2, true);


--
-- Name: auditoria_configuracion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auditoria_configuracion_id_seq', 19, true);


--
-- Name: codigos_recuperacion_password_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.codigos_recuperacion_password_id_seq', 7, true);


--
-- Name: comentarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.comentarios_id_seq', 5, true);


--
-- Name: companias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.companias_id_seq', 6, true);


--
-- Name: configuracion_sistema_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.configuracion_sistema_id_seq', 1, true);


--
-- Name: enlaces_compartidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enlaces_compartidos_id_seq', 1, false);


--
-- Name: historial_tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.historial_tickets_id_seq', 83, true);


--
-- Name: proyectos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.proyectos_id_seq', 14, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: solicitudes_recurso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.solicitudes_recurso_id_seq', 3, true);


--
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tickets_id_seq', 29, true);


--
-- Name: tipos_incidencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tipos_incidencia_id_seq', 5, true);


--
-- Name: usuario_proyectos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuario_proyectos_id_seq', 43, true);


--
-- Name: usuario_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuario_roles_id_seq', 18, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 18, true);


--
-- Name: adjuntos adjuntos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT adjuntos_pkey PRIMARY KEY (id);


--
-- Name: auditoria_configuracion auditoria_configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_configuracion
    ADD CONSTRAINT auditoria_configuracion_pkey PRIMARY KEY (id);


--
-- Name: codigos_recuperacion_password codigos_recuperacion_password_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.codigos_recuperacion_password
    ADD CONSTRAINT codigos_recuperacion_password_pkey PRIMARY KEY (id);


--
-- Name: comentarios comentarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT comentarios_pkey PRIMARY KEY (id);


--
-- Name: companias companias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companias
    ADD CONSTRAINT companias_pkey PRIMARY KEY (id);


--
-- Name: configuracion_sistema configuracion_sistema_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.configuracion_sistema
    ADD CONSTRAINT configuracion_sistema_pkey PRIMARY KEY (id);


--
-- Name: enlaces_compartidos enlaces_compartidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enlaces_compartidos
    ADD CONSTRAINT enlaces_compartidos_pkey PRIMARY KEY (id);


--
-- Name: enlaces_compartidos enlaces_compartidos_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enlaces_compartidos
    ADD CONSTRAINT enlaces_compartidos_token_key UNIQUE (token);


--
-- Name: historial_tickets historial_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_tickets
    ADD CONSTRAINT historial_tickets_pkey PRIMARY KEY (id);


--
-- Name: proyectos proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT proyectos_pkey PRIMARY KEY (id);


--
-- Name: roles roles_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nombre_key UNIQUE (nombre);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: solicitudes_recurso solicitudes_recurso_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes_recurso
    ADD CONSTRAINT solicitudes_recurso_pkey PRIMARY KEY (id);


--
-- Name: solicitudes_recurso solicitudes_recurso_ticket_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes_recurso
    ADD CONSTRAINT solicitudes_recurso_ticket_id_key UNIQUE (ticket_id);


--
-- Name: tickets tickets_numero_ticket_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_numero_ticket_key UNIQUE (numero_ticket);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: tipos_incidencia tipos_incidencia_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_incidencia
    ADD CONSTRAINT tipos_incidencia_nombre_key UNIQUE (nombre);


--
-- Name: tipos_incidencia tipos_incidencia_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tipos_incidencia
    ADD CONSTRAINT tipos_incidencia_pkey PRIMARY KEY (id);


--
-- Name: companias uk_companias_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companias
    ADD CONSTRAINT uk_companias_nombre UNIQUE (nombre);


--
-- Name: proyectos uk_proyecto_compania_nombre; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT uk_proyecto_compania_nombre UNIQUE (compania_id, nombre);


--
-- Name: usuario_proyectos uk_usuario_proyecto; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_proyectos
    ADD CONSTRAINT uk_usuario_proyecto UNIQUE (usuario_id, proyecto_id);


--
-- Name: usuario_roles uq_usuario_rol; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id);


--
-- Name: usuario_proyectos usuario_proyectos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_proyectos
    ADD CONSTRAINT usuario_proyectos_pkey PRIMARY KEY (id);


--
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_correo_key UNIQUE (correo);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: idx_proyecto_compania; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_proyecto_compania ON public.proyectos USING btree (compania_id);


--
-- Name: idx_solicitudes_recurso_estado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_solicitudes_recurso_estado ON public.solicitudes_recurso USING btree (estado_recurso);


--
-- Name: idx_usuario_proyecto_proyecto; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuario_proyecto_proyecto ON public.usuario_proyectos USING btree (proyecto_id);


--
-- Name: idx_usuario_proyecto_usuario; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usuario_proyecto_usuario ON public.usuario_proyectos USING btree (usuario_id);


--
-- Name: tickets fk3k7gntl8exxbqrf4qbqkq9tx6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk3k7gntl8exxbqrf4qbqkq9tx6 FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- Name: usuario_proyectos fk9eeykog2xs15f8rbb6bo311so; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_proyectos
    ADD CONSTRAINT fk9eeykog2xs15f8rbb6bo311so FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: adjuntos fk_adjuntos_ticket; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.adjuntos
    ADD CONSTRAINT fk_adjuntos_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


--
-- Name: comentarios fk_comentario_ticket; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fk_comentario_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: comentarios fk_comentario_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comentarios
    ADD CONSTRAINT fk_comentario_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: enlaces_compartidos fk_enlace_creado_por; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enlaces_compartidos
    ADD CONSTRAINT fk_enlace_creado_por FOREIGN KEY (creado_por) REFERENCES public.usuarios(id);


--
-- Name: enlaces_compartidos fk_enlace_ticket; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enlaces_compartidos
    ADD CONSTRAINT fk_enlace_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


--
-- Name: historial_tickets fk_historial_ticket; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_tickets
    ADD CONSTRAINT fk_historial_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: historial_tickets fk_historial_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_tickets
    ADD CONSTRAINT fk_historial_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: usuario_roles fk_rol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- Name: solicitudes_recurso fk_solicitud_recurso_ticket; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitudes_recurso
    ADD CONSTRAINT fk_solicitud_recurso_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


--
-- Name: tickets fk_ticket_agente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk_ticket_agente FOREIGN KEY (agente_asignado_id) REFERENCES public.usuarios(id);


--
-- Name: tickets fk_ticket_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk_ticket_cliente FOREIGN KEY (cliente_id) REFERENCES public.usuarios(id);


--
-- Name: tickets fk_ticket_tipo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fk_ticket_tipo FOREIGN KEY (tipo_incidencia_id) REFERENCES public.tipos_incidencia(id);


--
-- Name: usuario_roles fk_usuario; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id);


--
-- Name: proyectos fkf3oha5gagddmp7p8ke0fatffy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.proyectos
    ADD CONSTRAINT fkf3oha5gagddmp7p8ke0fatffy FOREIGN KEY (compania_id) REFERENCES public.companias(id);


--
-- Name: usuario_proyectos fkklkudv208vsvl500h2cxu5wq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario_proyectos
    ADD CONSTRAINT fkklkudv208vsvl500h2cxu5wq7 FOREIGN KEY (proyecto_id) REFERENCES public.proyectos(id);


--
-- PostgreSQL database dump complete
--

\unrestrict FxUaoVg1UNryePJkaF31RShTii6G4Miu2qNkEQHI6c9lhinZKmNTuio10kzKOve

